version: 2
updates:

  # Maintain dependencies for Git Submodules
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "monthly"

  # Maintain requirements files for gym_exps
  - package-ecosystem: "pip"
    directory: "/gym_exps/requirements"
    schedule:
      interval: "weekly"
